CXX=g++
CXXFLAGS=-O3 -std=c++11

RGB_LIB_DISTRIBUTION=matrix
RGB_LIBRARY_NAME=rgbmatrix

RGB_INCDIR=$(RGB_LIB_DISTRIBUTION)/include
RGB_LIBDIR=$(RGB_LIB_DISTRIBUTION)/lib
RGB_LIBRARY=$(RGB_LIBDIR)/lib$(RGB_LIBRARY_NAME).a

LDFLAGS+=-L$(RGB_LIBDIR) -l$(RGB_LIBRARY_NAME) -I$(RGB_INCDIR) -lrt -lm -lpthread

all: $(RGB_LIBRARY) rgb-binary

$(RGB_LIBRARY):
	$(MAKE) CXXFLAGS='$(CXXFLAGS)' -C $(RGB_LIBDIR)

rgb-binary: $(RGB_LIBRARY)
	$(CXX) rgb.cpp $(CXXFLAGS) $(LDFLAGS) -o ./$@
